resilio-sync:
    image: resilio-sync:latest
    container_name: sync
    build:
        context: ./
        dockerfile: Dockerfile
    domainname: ${DOMAINNAME}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "55555"
      - "3838:3838"
    environment:
      - DEVICE_NAME=${DEVICE_NAME}
    volumes:
      - syncdata:/usr/share/resilio-sync/
      - ./config/:/tmp/resilio-config/

volumes:
  syncdata:
    driver: local
